[2022-03-16 02:27:45,931] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-03-16T02:27:44.000006+00:00 [queued]>
[2022-03-16 02:27:45,953] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-03-16T02:27:44.000006+00:00 [queued]>
[2022-03-16 02:27:45,954] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 02:27:45,955] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-16 02:27:45,957] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 02:27:45,976] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2022-03-16 02:27:44.000006+00:00
[2022-03-16 02:27:45,987] {standard_task_runner.py:52} INFO - Started process 85 to run task
[2022-03-16 02:27:45,993] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', 'manual__2022-03-16T02:27:44.000006+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmp77ijszmn', '--error-file', '/tmp/tmpqdbpnas5']
[2022-03-16 02:27:45,994] {standard_task_runner.py:77} INFO - Job 39: Subtask load_seed_data_once
[2022-03-16 02:27:46,089] {logging_mixin.py:109} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-03-16T02:27:44.000006+00:00 [running]> on host 812778d1d7d0
[2022-03-16 02:27:46,220] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_init_once_seed_data
AIRFLOW_CTX_TASK_ID=load_seed_data_once
AIRFLOW_CTX_EXECUTION_DATE=2022-03-16T02:27:44.000006+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-16T02:27:44.000006+00:00
[2022-03-16 02:27:46,222] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-16 02:27:46,224] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /dbt && dbt seed --profiles-dir .']
[2022-03-16 02:27:46,242] {subprocess.py:85} INFO - Output:
[2022-03-16 02:27:52,581] {subprocess.py:89} INFO - 02:27:52  Running with dbt=1.0.0
[2022-03-16 02:27:52,708] {subprocess.py:89} INFO - 02:27:52  Partial parse save file not found. Starting full parse.
[2022-03-16 02:27:55,645] {subprocess.py:89} INFO - 02:27:55  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2022-03-16 02:27:55,645] {subprocess.py:89} INFO - There are 2 unused configuration paths:
[2022-03-16 02:27:55,646] {subprocess.py:89} INFO - - models.my_new_project.analysis
[2022-03-16 02:27:55,646] {subprocess.py:89} INFO - - models.my_new_project.transform
[2022-03-16 02:27:55,647] {subprocess.py:89} INFO - 
[2022-03-16 02:27:55,680] {subprocess.py:89} INFO - 02:27:55  Found 2 models, 4 tests, 0 snapshots, 0 analyses, 579 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
[2022-03-16 02:27:55,683] {subprocess.py:89} INFO - 02:27:55
[2022-03-16 02:27:55,685] {subprocess.py:89} INFO - 02:27:55  [WARNING]: Nothing to do. Try checking your model configs and model specification args
[2022-03-16 02:27:55,706] {subprocess.py:89} INFO - 02:27:55
[2022-03-16 02:27:55,709] {subprocess.py:89} INFO - 02:27:55  Completed successfully
[2022-03-16 02:27:55,710] {subprocess.py:89} INFO - 02:27:55
[2022-03-16 02:27:55,711] {subprocess.py:89} INFO - 02:27:55  Done. PASS=0 WARN=0 ERROR=0 SKIP=0 TOTAL=0
[2022-03-16 02:27:56,974] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-16 02:27:57,001] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20220316T022744, start_date=20220316T022745, end_date=20220316T022757
[2022-03-16 02:27:57,038] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-16 02:27:57,069] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
